/*
 * Pixel Dungeon
 * Copyright (C) 2012-2015 Oleg Dolya
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */
package com.watabou.pixeldungeon.web;

import com.github.xpenatan.gdx.backends.teavm.config.AssetFileHandle;
import com.github.xpenatan.gdx.backends.teavm.config.TeaBuildConfiguration;
import com.github.xpenatan.gdx.backends.teavm.config.TeaBuilder;
import com.github.xpenatan.gdx.backends.teavm.config.plugins.TeaReflectionSupplier;
import java.io.File;
import java.io.IOException;
import org.teavm.tooling.TeaVMTool;
import org.teavm.vm.TeaVMOptimizationLevel;

/**
 * Runs TeaVM to compile :web (and its transitive :core / :noosa-gdx) to
 * JavaScript. Output: web/build/dist/{index.html, app.js, assets/}.
 *
 * The game uses reflection on {@link com.watabou.utils.Bundle.Bundlable}
 * subclasses (instantiation by name when loading a save). We register
 * the whole watabou tree so every mob/item/level/buff/blob/plant/heap
 * implementation is reachable at runtime.
 */
public class BuildTeaVM {

	public static void main( String[] args ) throws IOException {

		// Reflection roots
		TeaReflectionSupplier.addReflectionClass( "com.watabou" );
		TeaReflectionSupplier.addReflectionClass( "com.badlogic.gdx.math" );

		TeaBuildConfiguration cfg = new TeaBuildConfiguration();
		cfg.assetsPath.add( new AssetFileHandle( "../assets" ) );
		cfg.webappPath = new File( "build/dist" ).getCanonicalPath();
		cfg.mainClass = WebLauncher.class.getName();
		cfg.htmlTitle = "Pixel Dungeon: 100 Floors";
		cfg.htmlWidth = 960;
		cfg.htmlHeight = 640;

		// Room.Type invokes level painters via Method.invoke on their static
		// paint() method, and Bestiary instantiates mobs by name. Classes only
		// reached through reflection are not fully code-generated by TeaVM
		// (their static initializers are emitted as "$callClinit is not
		// defined"), so we force full generation of the reflection-only trees.
		cfg.classesToPreserve.add( "com.watabou.pixeldungeon.levels.painters" );
		cfg.classesToPreserve.add( "com.watabou.pixeldungeon.actors.mobs" );
		cfg.classesToPreserve.add( "com.watabou.pixeldungeon.actors.blobs" );
		cfg.classesToPreserve.add( "com.watabou.pixeldungeon.actors.buffs" );
		cfg.classesToPreserve.add( "com.watabou.pixeldungeon.plants" );

		TeaVMTool tool = TeaBuilder.config( cfg );
		tool.setObfuscated( false );
		tool.setOptimizationLevel( TeaVMOptimizationLevel.SIMPLE );
		tool.setMainClass( WebLauncher.class.getName() );

		TeaBuilder.build( tool );

		injectCsp( new File( "build/dist/webapp/index.html" ) );
	}

	/**
	 * Adds a permissive Content-Security-Policy meta to the generated
	 * index.html. TeaVM's JS/WASM bridge needs eval / wasm-unsafe-eval; some
	 * browser environments (privacy extensions, corporate proxies) inject a
	 * restrictive CSP that blocks it and stalls the app. An explicit meta in
	 * our own page takes precedence and makes the bundle portable. This is a
	 * single-player game with no user-supplied content, so unsafe-eval carries
	 * no injection risk here.
	 */
	private static void injectCsp( File indexHtml ) {
		try {
			if (!indexHtml.exists()) return;
			byte[] raw = java.nio.file.Files.readAllBytes( indexHtml.toPath() );
			String html = new String( raw, java.nio.charset.StandardCharsets.UTF_8 );
			if (html.contains( "Content-Security-Policy" )) return;
			String meta = "<meta http-equiv=\"Content-Security-Policy\" "
					+ "content=\"default-src 'self' data: blob:; "
					+ "script-src 'self' 'unsafe-eval' 'wasm-unsafe-eval' 'unsafe-inline' blob:; "
					+ "style-src 'self' 'unsafe-inline'; "
					+ "img-src 'self' data: blob:; "
					+ "media-src 'self' data: blob:; "
					+ "connect-src 'self' data: blob:;\">";
			html = html.replaceFirst( "<head>", "<head>\n    " + meta );
			java.nio.file.Files.write( indexHtml.toPath(),
					html.getBytes( java.nio.charset.StandardCharsets.UTF_8 ) );
			System.out.println( "Injected permissive CSP meta into index.html" );
		} catch (Exception e) {
			System.err.println( "Could not inject CSP meta: " + e.getMessage() );
		}
	}
}
