/*
 * Pixel Dungeon
 * Copyright (C) 2012-2015 Oleg Dolya
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 */
package com.watabou.pixeldungeon.web;

import com.github.xpenatan.gdx.backends.teavm.config.AssetFileHandle;
import com.github.xpenatan.gdx.backends.teavm.config.TeaBuildConfiguration;
import com.github.xpenatan.gdx.backends.teavm.config.TeaBuilder;
import com.github.xpenatan.gdx.backends.teavm.config.plugins.TeaReflectionSupplier;
import java.io.File;
import java.io.IOException;
import org.teavm.tooling.TeaVMTool;
import org.teavm.vm.TeaVMOptimizationLevel;

/**
 * Runs TeaVM to compile :web (and its transitive :core / :noosa-gdx) to
 * JavaScript. Output: web/build/dist/{index.html, app.js, assets/}.
 *
 * The game uses reflection on {@link com.watabou.utils.Bundle.Bundlable}
 * subclasses (instantiation by name when loading a save). We register
 * the whole watabou tree so every mob/item/level/buff/blob/plant/heap
 * implementation is reachable at runtime.
 */
public class BuildTeaVM {

	public static void main( String[] args ) throws IOException {

		// Reflection roots
		TeaReflectionSupplier.addReflectionClass( "com.watabou" );
		TeaReflectionSupplier.addReflectionClass( "com.badlogic.gdx.math" );

		TeaBuildConfiguration cfg = new TeaBuildConfiguration();
		cfg.assetsPath.add( new AssetFileHandle( "../assets" ) );
		cfg.webappPath = new File( "build/dist" ).getCanonicalPath();
		cfg.mainClass = WebLauncher.class.getName();
		cfg.htmlTitle = "Pixel Dungeon: 100 Floors";
		cfg.htmlWidth = 960;
		cfg.htmlHeight = 640;

		// Room.Type invokes level painters via Method.invoke on their static
		// paint() method, and Bestiary instantiates mobs by name. Classes only
		// reached through reflection are not fully code-generated by TeaVM
		// (their static initializers are emitted as "$callClinit is not
		// defined"), so we force full generation of the reflection-only trees.
		cfg.classesToPreserve.add( "com.watabou.pixeldungeon.levels.painters" );
		cfg.classesToPreserve.add( "com.watabou.pixeldungeon.actors.mobs" );
		cfg.classesToPreserve.add( "com.watabou.pixeldungeon.actors.blobs" );
		cfg.classesToPreserve.add( "com.watabou.pixeldungeon.actors.buffs" );
		cfg.classesToPreserve.add( "com.watabou.pixeldungeon.plants" );

		TeaVMTool tool = TeaBuilder.config( cfg );
		tool.setObfuscated( false );
		tool.setOptimizationLevel( TeaVMOptimizationLevel.SIMPLE );
		tool.setMainClass( WebLauncher.class.getName() );

		TeaBuilder.build( tool );

		rewriteWebapp( new File( "build/dist/webapp" ) );
	}

	/**
	 * Rewrites the gdx-teavm generated index.html into a CSP-clean page.
	 *
	 * The generated page bootstraps the game with an inline {@code <script>},
	 * inline {@code <style>}, and inline {@code onload}/{@code oncontextmenu}
	 * handlers. Any externally-imposed Content-Security-Policy (privacy
	 * extension, corporate proxy, GitHub Pages / itch.io defaults) with
	 * {@code script-src 'self'} blocks all of those, so the game never boots
	 * (broken loading logo, white/black screen). A page-level meta cannot
	 * loosen an externally-supplied CSP.
	 *
	 * We therefore externalise everything: the inline style block goes to
	 * style.css, the inline bootstrap goes to bootstrap.js (with the event
	 * handlers attached via addEventListener), and the page itself becomes
	 * fully static. The only remaining requirement is 'wasm-unsafe-eval' for
	 * the libGDX WASM image-decoding module, which virtually every restrictive
	 * CSP still allows. A self meta is also written for the common case where
	 * no external CSP is present.
	 */
	private static void rewriteWebapp( File webapp ) {
		try {
			File indexHtml = new File( webapp, "index.html" );
			if (!indexHtml.exists()) return;

			String html = new String(
					java.nio.file.Files.readAllBytes( indexHtml.toPath() ),
					java.nio.charset.StandardCharsets.UTF_8 );

			// Extract the generated inline <style> block into style.css.
			String css = "";
			int styleStart = html.indexOf( "<style>" );
			int styleEnd = html.indexOf( "</style>" );
			if (styleStart >= 0 && styleEnd > styleStart) {
				css = html.substring( styleStart + "<style>".length(), styleEnd );
			}
			java.nio.file.Files.write( new File( webapp, "style.css" ).toPath(),
					css.getBytes( java.nio.charset.StandardCharsets.UTF_8 ) );

			// External bootstrap: progress bar + game start, no inline handlers.
			String bootstrap =
					"(function () {\n" +
					"  document.addEventListener('contextmenu', function (e) { e.preventDefault(); });\n" +
					"  var maxPercentage = 25, delay = 500;\n" +
					"  var bar = document.getElementById('progress-bar');\n" +
					"  function barUpdater() {\n" +
					"    if (!bar) return;\n" +
					"    var p = parseInt(bar.style.width, 10) || 0;\n" +
					"    if (p < maxPercentage) { bar.style.width = (p + 1) + '%'; delay += 25; setTimeout(barUpdater, delay); }\n" +
					"  }\n" +
					"  if (bar) { bar.style.width = '0%'; setTimeout(barUpdater, delay); }\n" +
					"  window.addEventListener('load', function () { if (typeof main === 'function') { main(); } });\n" +
					"})();\n";
			java.nio.file.Files.write( new File( webapp, "bootstrap.js" ).toPath(),
					bootstrap.getBytes( java.nio.charset.StandardCharsets.UTF_8 ) );

			// Fully static, CSP-clean index.html.
			String page =
					"<!DOCTYPE html>\n" +
					"<html>\n" +
					"<head>\n" +
					"    <title>Pixel Dungeon: 100 Floors</title>\n" +
					"    <meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\">\n" +
					"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\">\n" +
					"    <meta http-equiv=\"Content-Security-Policy\" content=\"" +
					"default-src 'self' data: blob:; " +
					"script-src 'self' 'wasm-unsafe-eval'; " +
					"style-src 'self'; " +
					"img-src 'self' data: blob:; " +
					"media-src 'self' data: blob:; " +
					"connect-src 'self' data: blob:;\">\n" +
					"    <link rel=\"stylesheet\" href=\"style.css\">\n" +
					"</head>\n" +
					"<body>\n" +
					"<div>\n" +
					"    <div id=\"progress\">\n" +
					"        <img id=\"progress-img\" src=\"startup-logo.png\" alt=\"loading\">\n" +
					"        <div id=\"progress-box\"><div id=\"progress-bar\"></div></div>\n" +
					"    </div>\n" +
					"    <canvas id=\"canvas\" width=\"960\" height=\"640\"></canvas>\n" +
					"</div>\n" +
					"<script type=\"text/javascript\" charset=\"utf-8\" src=\"teavm/app.js\"></script>\n" +
					"<script type=\"text/javascript\" charset=\"utf-8\" src=\"bootstrap.js\"></script>\n" +
					"</body>\n" +
					"</html>\n";
			java.nio.file.Files.write( indexHtml.toPath(),
					page.getBytes( java.nio.charset.StandardCharsets.UTF_8 ) );

			System.out.println( "Rewrote index.html CSP-clean (external style.css + bootstrap.js)" );
		} catch (Exception e) {
			System.err.println( "Could not rewrite webapp index.html: " + e.getMessage() );
		}
	}
}
